<a href="https://colab.research.google.com/github/Satish055/Machine_Learning_D/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MULTIPLE LINEAR REGRESSION MODEL**

Linear regerssion is a Statistical Model to predict the relationship between independent and dependent variables

```
# This is formatted as code
```



Importing Necessary Libraries for Machine Learning

In [5]:
# Importing the necessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [9]:
data=pd.read_csv('/content/1000_Companies.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [12]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

Finding the Missing Values from Dataset

In [13]:
data.isnull().sum()*100

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [15]:
# Datatypes
data.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

Information of dataset

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        1000 non-null   float64
 1   Administration   1000 non-null   float64
 2   Marketing Spend  1000 non-null   float64
 3   State            1000 non-null   object 
 4   Profit           1000 non-null   float64
dtypes: float64(4), object(1)
memory usage: 39.2+ KB


In [ ]:
# Describe of dataset

In [18]:
data.describe()

R&D Spend  Administration  Marketing Spend         Profit
count    1000.000000     1000.000000      1000.000000    1000.000000
mean    81668.927200   122963.897612    226205.058419  119546.164656
std     46537.567891    12613.927535     91578.393542   42888.633848
min         0.000000    51283.140000         0.000000   14681.400000
25%     43084.500000   116640.684850    150969.584600   85943.198543
50%     79936.000000   122421.612150    224517.887350  117641.466300
75%    124565.500000   129139.118000    308189.808525  155577.107425
max    165349.200000   321652.140000    471784.100000  476485.430000

**Extracting the dataset into independent and dependent variables**

In [20]:
X=data.iloc[:,:-1].values
y=data.iloc[:,4].values

In [21]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       ...,
       [100275.47, 241926.31, 227142.82, 'California'],
       [128456.23, 321652.14, 281692.32, 'California'],
       [161181.72, 270939.86, 295442.17, 'New York']], dtype=object)

In [23]:
y

array([192261.83   , 191792.06   , 191050.39   , 182901.99   ,
       166187.94   , 156991.12   , 156122.51   , 155752.6    ,
       152211.77   , 149759.96   , 146121.95   , 144259.4    ,
       141585.52   , 134307.35   , 132602.65   , 129917.04   ,
       126992.93   , 125370.37   , 124266.9    , 122776.86   ,
       118474.03   , 111313.02   , 110352.25   , 108733.99   ,
       108552.04   , 107404.34   , 105733.54   , 105008.31   ,
       103282.38   , 101004.64   ,  99937.59   ,  97483.56   ,
        97427.84   ,  96778.92   ,  96712.8    ,  96479.51   ,
        90708.19   ,  89949.14   ,  81229.06   ,  81005.76   ,
        78239.91   ,  77798.83   ,  71498.49   ,  69758.98   ,
        65200.33   ,  64926.08   ,  49490.75   ,  42559.73   ,
        35673.41   ,  14681.4    , 123485.2464 ,  82155.48418,
       125867.0108 , 104976.1696 ,  89803.10053,  75297.23305,
       114284.5283 , 171985.0761 ,  72337.96774, 169566.5772 ,
       158670.9451 , 114522.8756 ,  85842.60573, 101106

In [27]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
lc_x=LabelEncoder()
X[:,3]=lc_x.fit_transform(X[:,3])

In [37]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("State", OneHotEncoder(), [3])], remainder = 'passthrough')
X = ct.fit_transform(X).toarray()

In [30]:
# Avoid Dummy variable Trap then drop one columns

In [38]:
X=X[:,1:]

In [39]:
X

array([[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.6534920e+05, 4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.6259770e+05, 4.4389853e+05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.5344151e+05, 4.0793454e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0027547e+05, 2.2714282e+05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.2845623e+05, 2.8169232e+05],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.6118172e+05, 2.9544217e+05]])

**Splitting the dataset into Training and test set**

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [42]:
X_train.shape

(800, 1001)

In [43]:
X_test.shape

(200, 1001)

In [44]:
y_train.shape

(800,)

In [45]:
y_test.shape

(200,)

**Fitting the Multiple_Linear Regression to the training set**

In [46]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [47]:
m=regressor.coef_
c=regressor.intercept_

In [48]:
m

array([-1.20053281e+04,  1.35005932e+04, -3.96894294e+03, ...,
       -2.49056509e+03,  8.17033476e-01,  2.13982530e-02])

In [49]:
c

np.float64(49726.430188082595)

In [50]:
# Predicting the test set results

In [51]:
y_pred=regressor.predict(X_test)
y_pred

array([ 91365.90932391,  90002.03651685,  96471.20538886, 175760.24597092,
        83193.25614755, 110359.98879321, 113707.70469405,  93049.07771297,
       164398.19150403,  53272.62317784,  68519.96692532, 150639.75169441,
       128499.4708054 ,  60905.79722086, 179110.39590976,  75095.85145856,
       118313.64872886, 166167.76656087, 150815.5877398 , 181874.47482561,
        99074.05017288,  87244.24965569, 181073.25583091,  85719.01241375,
       106584.80719568, 102811.62604152,  48093.82727123,  56656.53145547,
        70466.64000504, 192072.84726544, 120844.8387262 , 113305.46425653,
       101273.79777907, 138029.29275074,  65539.01648168, 110437.81224695,
       185821.03691432, 171520.99626163, 174723.3936428 , 117736.85670602,
        96516.12190677, 167045.82941833, 109303.96959146,  50243.60673787,
       116578.98105119,  60200.25697782, 158491.67644439,  78597.39796356,
       159803.19163931, 131206.49543624, 184962.31038334, 174688.20246304,
        95321.91295022,  

**Calculating the Metrics for accuaracy sore**

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
print(f"Mean_Absolute Error of Model is {mae}")
print(f"Mean_Squared Error of Model is {mse}")
print(f"Root_Mean_Squared Error of Model is {rmse}")
print(f"R2 Score of Model is {round((r2)*100)}%")

Mean_Absolute Error of Model is 2637.0733818143513
Mean_Squared Error of Model is 429825708.7686387
Root_Mean_Squared Error of Model is 20732.238392625113
R2 Score of Model is 80%
